FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-tk \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY client.py .
COPY assets ./assets

ENV DISPLAY=:99

CMD ["python", "client.py"]

